#!/usr/bin/env python3
"""
TIKTOK BATCH DOWNLOADER
────────────────────────────────────────────────────────────────────────
Downloads TikTok videos from a .txt URL file (generated by tiktok_url_collector.js)

REQUIREMENTS:
    pip install yt-dlp

BASIC USAGE:
    python scripts/tiktok_batch_download.py --links links/TikTokLinks.txt --out "D:\\Products Reels\\wireless_earbuds"

USAGE WITH LIMIT:
    python scripts/tiktok_batch_download.py --links links/TikTokLinks.txt --out "D:\\Products Reels\\wireless_earbuds" --max 20

OUTPUT STRUCTURE:
    D:\\Products Reels\\
    └── wireless_earbuds\\
        ├── @username1__title__id.mp4
        ├── @username2__title__id.mp4
        └── download_log.csv          ← log with status of each download
────────────────────────────────────────────────────────────────────────
"""

import argparse
import csv
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path


# ── yt-dlp configuration ──────────────────────────────────────────────────────

YDL_BASE_ARGS = [
    "--no-playlist",
    "--merge-output-format", "mp4",
    "--no-warnings",
    "--quiet",
    "--no-mtime",            # do not overwrite the file timestamp
    "--restrict-filenames",  # safe filenames (no special characters)
    "--no-check-certificates",
    "--sleep-interval", "2",          # 2s pause between downloads (avoid bans)
    "--max-sleep-interval", "5",      # random pause up to 5s
]

# Filename template: @username__description_truncated__videoID.mp4
OUTPUT_TEMPLATE = "%(uploader)s__%(title).60s__%(id)s.%(ext)s"

# Metadata print template (populated by yt-dlp --print, pipe-separated)
METADATA_PRINT = "%(uploader_id)s|%(view_count)s|%(like_count)s|%(comment_count)s|%(repost_count)s"

# Command to invoke yt-dlp — set by check_ytdlp() at startup
YDL_CMD: list[str] = []

# Cookie args — set by main() based on --browser argument
COOKIE_ARGS: list[str] = []


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe_int(val: str) -> int:
    """Convert string to int, returning 0 on failure (handles 'N/A', 'None', etc.)."""
    try:
        return int(val)
    except (ValueError, TypeError):
        return 0


def check_ytdlp():
    """Verify that yt-dlp is installed and set YDL_CMD accordingly."""
    global YDL_CMD

    # Attempt 1: yt-dlp binary on PATH
    try:
        result = subprocess.run(
            ["yt-dlp", "--version"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            print(f"[✓] yt-dlp {result.stdout.strip()}")
            YDL_CMD = ["yt-dlp"]
            return
    except FileNotFoundError:
        pass

    # Attempt 2: python -m yt_dlp (Windows pip install fallback)
    try:
        result = subprocess.run(
            [sys.executable, "-m", "yt_dlp", "--version"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            print(f"[✓] yt-dlp {result.stdout.strip()} (via python -m yt_dlp)")
            YDL_CMD = [sys.executable, "-m", "yt_dlp"]
            return
    except FileNotFoundError:
        pass

    print("[✗] yt-dlp not found. Install with: pip install yt-dlp")
    sys.exit(1)


def _is_valid_url(u: str) -> bool:
    return bool(u and "tiktok.com" in u and "/video/" in u)


def _read_txt(path: Path) -> list[str]:
    lines = path.read_text(encoding="utf-8").strip().splitlines()
    return [l.strip() for l in lines if _is_valid_url(l.strip())]


def _read_csv(path: Path) -> list[str]:
    """Read URLs from a CSV file. Expects a 'url' column; falls back to first column."""
    urls = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames and "url" in reader.fieldnames:
            for row in reader:
                u = row.get("url", "").strip()
                if _is_valid_url(u):
                    urls.append(u)
        else:
            # Fallback: treat every non-header line as a potential URL
            f.seek(0)
            next(f, None)  # skip header row
            for line in f:
                u = line.strip()
                if _is_valid_url(u):
                    urls.append(u)
    return urls


def load_urls(links_files: list[str], max_videos: int | None) -> list[str]:
    """Load and deduplicate URLs from one or more .txt or .csv files."""
    all_urls: list[str] = []

    for links_file in links_files:
        path = Path(links_file)
        if not path.exists():
            print(f"[!] File not found, skipping: {links_file}")
            continue
        if path.suffix.lower() == ".csv":
            file_urls = _read_csv(path)
        else:
            file_urls = _read_txt(path)
        print(f"[i] {path.name}: {len(file_urls)} valid URLs")
        all_urls.extend(file_urls)

    urls = list(dict.fromkeys(all_urls))  # deduplicate cross-file, preserve order
    print(f"[i] Total unique URLs: {len(urls)}")

    if max_videos and len(urls) > max_videos:
        urls = urls[:max_videos]
        print(f"[i] Limited to: {max_videos}")

    return urls


def fetch_metadata(url: str) -> dict:
    """Fetch engagement metadata for a URL using yt-dlp --print --skip-download."""
    cmd = [
        *YDL_CMD,
        "--no-playlist",
        "--no-warnings",
        "--quiet",
        "--no-check-certificates",
        "--skip-download",
        *COOKIE_ARGS,
        "--print", METADATA_PRINT,
        url
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        if result.returncode == 0:
            line = result.stdout.strip().splitlines()[0] if result.stdout.strip() else ""
            parts = line.split("|")
            if len(parts) == 5:
                return {
                    "username": parts[0],
                    "views":    _safe_int(parts[1]),
                    "likes":    _safe_int(parts[2]),
                    "comments": _safe_int(parts[3]),
                    "shares":   _safe_int(parts[4]),
                }
    except Exception:
        pass
    return {"username": "", "views": 0, "likes": 0, "comments": 0, "shares": 0}


def download_video(url: str, output_dir: str) -> dict:
    """Download a single video. Returns a dict with status."""
    cmd = [
        *YDL_CMD,
        *YDL_BASE_ARGS,
        *COOKIE_ARGS,
        "--output", str(Path(output_dir) / OUTPUT_TEMPLATE),
        url
    ]

    start = time.time()
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    elapsed = round(time.time() - start, 1)

    success = result.returncode == 0
    error = ""
    if not success:
        # Extract main error message
        stderr = result.stderr.strip()
        stdout = result.stdout.strip()
        error = (stderr or stdout)[:200]

    return {
        "url": url,
        "status": "ok" if success else "error",
        "error": error,
        "elapsed_s": elapsed,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
    }


def save_log(log_entries: list[dict], output_dir: str):
    """Save the CSV log to the output folder."""
    log_path = Path(output_dir) / "download_log.csv"
    fields = [
        "url", "status", "error", "elapsed_s", "timestamp",
        "username", "views", "likes", "comments", "shares"
    ]

    with open(log_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(log_entries)

    print(f"\n[✓] Log saved: {log_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Download TikTok videos from a URL file."
    )
    parser.add_argument(
        "--links", required=True, nargs="+",
        help="One or more .txt or .csv files containing TikTok URLs"
    )
    parser.add_argument(
        "--out", required=True,
        help='Destination folder (e.g. "D:\\Products Reels\\wireless_earbuds")'
    )
    parser.add_argument(
        "--max", type=int, default=None,
        help="Maximum number of videos to download (default: all)"
    )
    parser.add_argument(
        "--delay", type=float, default=2.0,
        help="Pause in seconds between downloads (default: 2)"
    )
    parser.add_argument(
        "--browser", default="chrome",
        choices=["chrome", "edge", "firefox", "brave", "opera", "chromium", "safari"],
        help="Browser to extract TikTok cookies from (default: chrome)"
    )
    parser.add_argument(
        "--cookies-file", default=None,
        help="Path to a cookies.txt file (alternative to --browser, works with Chrome open)"
    )
    args = parser.parse_args()

    # ── Setup ──────────────────────────────────────────────────────────────────
    global COOKIE_ARGS
    if args.cookies_file:
        cookies_path = Path(args.cookies_file)
        if not cookies_path.exists():
            print(f"[✗] Cookies file not found: {args.cookies_file}")
            sys.exit(1)
        COOKIE_ARGS = ["--cookies", str(cookies_path)]
        print(f"[i] Using cookies file: {cookies_path}")
    else:
        COOKIE_ARGS = ["--cookies-from-browser", args.browser]
        print(f"[i] Using cookies from browser: {args.browser}")

    check_ytdlp()

    output_dir = Path(args.out)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"[i] Output: {output_dir}")

    urls = load_urls(args.links, args.max)  # args.links is now a list

    if not urls:
        print("[!] No valid URLs found in the file.")
        sys.exit(0)

    # ── Download loop ──────────────────────────────────────────────────────────
    log = []
    ok_count = 0
    fail_count = 0

    print(f"\n{'─'*60}")
    print(f"Starting download of {len(urls)} videos...")
    print(f"{'─'*60}\n")

    for i, url in enumerate(urls, 1):
        print(f"[{i}/{len(urls)}] {url[:80]}...")

        entry = download_video(url, str(output_dir))

        if entry["status"] == "ok":
            ok_count += 1
            print(f"  ✓ Downloaded ({entry['elapsed_s']}s)")
            meta = fetch_metadata(url)
            entry.update(meta)
            print(f"     @{meta['username']} | views={meta['views']:,} | "
                  f"likes={meta['likes']:,} | comments={meta['comments']:,} | "
                  f"shares={meta['shares']:,}")
        else:
            fail_count += 1
            print(f"  ✗ Error: {entry['error'][:100]}")
            entry.update({"username": "", "views": 0, "likes": 0, "comments": 0, "shares": 0})

        log.append(entry)

        # Pause between downloads (avoid rate limiting)
        if i < len(urls):
            time.sleep(args.delay)

    # ── Summary ────────────────────────────────────────────────────────────────
    print(f"\n{'─'*60}")
    print(f"COMPLETE")
    print(f"  ✓ Downloaded:  {ok_count}")
    print(f"  ✗ Errors:      {fail_count}")
    print(f"  Total:         {len(urls)}")
    print(f"{'─'*60}")

    save_log(log, str(output_dir))

    # Show downloaded files
    mp4_files = sorted(output_dir.glob("*.mp4"))
    if mp4_files:
        print(f"\nFiles in folder ({len(mp4_files)} videos):")
        for f in mp4_files[:10]:
            size_mb = f.stat().st_size / (1024 * 1024)
            print(f"  {f.name[:70]} ({size_mb:.1f} MB)")
        if len(mp4_files) > 10:
            print(f"  ... and {len(mp4_files) - 10} more files")


if __name__ == "__main__":
    main()
